---

name: publish

on:
  repository_dispatch:
    types: dm-api

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Build
        uses: InformaticsMatters/squonk2-openapi-js-client-generator/build-client@main
        env:
          CI_PIPELINE_ID: ${{ github.event.client_payload.CI_PIPELINE_ID }}
          CI_COMMIT_TAG: ${{ github.event.client_payload.CI_COMMIT_TAG }}
          GITLAB_API: https://gitlab.com/api/v4/projects
          GITLAB_API_TOKEN: ${{ secrets.DATA_MANAGER_TOKEN }}
          GITLAB_PROJECT: 39606721
          OPENAPI_FILE: openapi.yaml
          OPENAPI_PATH: app%2Fopenapi
        with:
          API_NAME: data-manager-api
          API_TARGET_NAME: data-manager-api
      - name: Publish
        uses: InformaticsMatters/squonk2-openapi-js-client-generator/publish-client@main
        env:
          CI_COMMIT_TAG: ${{ github.event.client_payload.CI_COMMIT_TAG }}
          NODE_AUTH_TOKEN: ${{ secrets.NODE_AUTH_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Docs
        uses: InformaticsMatters/squonk2-openapi-js-client-generator/publish-docs@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
